### PR TITLE
Support passing additional props to the cards

### PR DESCRIPTION
**Pull request by Demven**
Now when we render cards there is no way to pass some extra data in addition to the mobiledoc section payload. And for https://github.com/dailybeast/thedailybeast/pull/1607 we need to pass `contentType` parameter to tell a mobiledoc card about the page where it's rendered, so that it could adapt to the page.

### CODE REVIEW

**Comment by Demven** [comment]
[[Feature] - Take 'Body' off the grid, put 'Body' components on the grid instead](https://trello.com/c/K091jBwo/1958-feature-take-body-off-the-grid-put-body-components-on-the-grid-instead)

**Review by dfairaizl — APPROVED** [review]
LGTM

**Comment by dfairaizl** [comment]
@Demven Published @dailybeast/mobiledoc-react-renderer 1.1.0

**Comment by Demven** [comment]
@dfairaizl Thanks for publishing!

**Pull request merged**
